launch_config:
  default_parameters:
    # 서버 기본값
    server:
      host: "127.0.1.1"
      port: 9988
      max_robots: 5
      interactive: false
    
    # 클라이언트 기본값
    client:
      communication_mode: "hybrid"
      enable_tcp: true
      enable_ros2: true
      auto_reconnect: true
    
    # 시스템 기본값
    system:
      domain_id: 0
      log_level: "INFO"
      enable_monitoring: true
  
  # 미리 정의된 로봇 설정
  predefined_robots:
    factory_robots:
      - robot_id: "factory_01"
        dobot_port: "/dev/ttyUSB0"
        position: [0, 0, 0]
      - robot_id: "factory_02"
        dobot_port: "/dev/ttyUSB1"
        position: [500, 0, 0]
      - robot_id: "factory_03"
        dobot_port: "/dev/ttyUSB2"
        position: [1000, 0, 0]
    
    lab_robots:
      - robot_id: "lab_alpha"
        dobot_port: "COM3"
        enable_simulation: false
      - robot_id: "lab_beta"
        dobot_port: "COM4"
        enable_simulation: false
    
    simulation_robots:
      - robot_id: "sim_01"
        enable_simulation: true
      - robot_id: "sim_02"
        enable_simulation: true
      - robot_id: "sim_03"
        enable_simulation: true