# config/server_config.yaml
dobot_multi_robot_server:
  ros__parameters:
    # TCP 서버 설정
    tcp_host: "127.0.1.1"
    tcp_port: 9988
    enable_tcp: true
    
    # ROS2 통신 설정
    enable_ros2: true
    
    # 로봇 관리 설정
    max_robots: 10
    task_timeout: 300.0        # 5분 (초)
    heartbeat_interval: 10.0   # 10초
    cleanup_interval: 60.0     # 1분
    
    # 작업 큐 설정
    max_queue_size: 100
    task_priority_levels: 5
    auto_assign_tasks: true
    
    # 로그 설정
    log_level: "INFO"          # DEBUG, INFO, WARN, ERROR
    enable_task_logging: true
    enable_robot_logging: true
    
    # 안전 설정
    emergency_stop_timeout: 5.0
    robot_timeout: 60.0        # 로봇 연결 타임아웃 (초)
    max_reconnect_attempts: 5
    
    # 성능 설정
    thread_pool_size: 4
    message_buffer_size: 4096