dobot_system:
  ros__parameters:
    # 네트워크 설정
    domain_id: 0
    use_multicast: true
    
    # 토픽 네임스페이스 설정
    robot_namespace: "/robot"
    system_namespace: "/dobot_system"
    
    # QoS 설정
    reliability_policy: "reliable"  # reliable, best_effort
    durability_policy: "volatile"   # volatile, transient_local
    history_policy: "keep_last"     # keep_last, keep_all
    queue_depth: 10
    
    # 시스템 모니터링
    enable_monitoring: true
    monitoring_interval: 30.0  # 30초
    
    # 성능 최적화
    executor_type: "multi_threaded"  # single_threaded, multi_threaded
    thread_count: 4
    
    # 보안 설정 (ROS2 Security 사용 시)
    enable_security: false
    security_policy: ""
    
    # 디버깅
    enable_debug_topics: false
    debug_level: 1